### ISSUE TITLE
Parse corequisites and anchor tags

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#12]
## Description

- Extend `CourseInfoParser` to extract corequisite courses from descriptions, similarly to prerequisites, and `CatalogSpider` to store that info
- Extend `CatalogSpider` to extract the anchor tag which precedes each title line in the catalog, and store that too
  - If the anchor tag is not present, then ignore that course listing (we assume that in these cases, the course is from another department)

## Tasks

- [x] Add corequisite parsing function to `CourseInfoParser`
- [x] Call the function from `CatalogSpider` and write to output
- [ ] Add selectors for anchor tags in `CatalogSpider` and write to output
