### ISSUE TITLE
Scraping postprocessing

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#14]
## Description

When running the command-line scraping script, after the Scrapy process finishes, do some postprocessing to generate an index of departments.

- During scraping, output a special JSON object containing the department code, department name, and link to the catalog page as the first line in each JSON Lines file
- After scraping, unless a dry run was specified, read each JSON Lines file using the [`jsonlines`](https://jsonlines.readthedocs.io/en/latest/) library
  - Store the first object in a department index dictionary keyed by department code
  - For each course in the department, add an entry to a course index dictionary with the course code as key and the department code as value (in cases where the same course is listed in multiple departments, overwrite the existing entry iff the new course object has an `anchor` field)
  - Write the two dictionaries to `index.json` in the output directory

## Tasks

- [x] Parse department name from its catalog page
- [x] Output index object when starting to crawl a new catalog page
- [x] Study and install `jsonlines` library
- [x] Add postprocessing step in command-line script which reads each `.jsonl` file in the output directory
- [x] Build department and course index dictionaries in the postprocessing step
- [x] Write to `index.json`
