### ISSUE TITLE
Course sequence listings

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#16]
## Description

- Properly handle listings for course sequences when scraping the catalog (multiple courses put together in one listing)

## Tasks

- [ ] Detect multi-course listings in postprocessor
- [ ] Extract separate course codes from title
- [ ] Extract separate units from title if possible
- [ ] Store an entry for each course code - duplicate all other course information

**Comment by wllmwu** [comment]
Currently doesn't seem to be worth the effort - there are fewer than 70 multi-course listings in the catalog, most of them are graduate courses with little or no connectedness to other courses, and the descriptions in the catalog tend to be written with references to e.g. "these courses" or "this sequence" which could become confusing if the courses were separated. Removing from the v1.2.0 milestone but leaving the issue open for now
