### ISSUE TITLE
All departments page

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#18]
## Description

- **As a** student,
- **I want** to see a list of departments,
- **So that** I can navigate the site in a familiar way (similar to the actual catalog).

## Tasks

- [x] #19
- [x] Create empty departments page
- [x] Use [`getStaticProps`](https://nextjs.org/docs/basic-features/data-fetching/get-static-props) to fetch department info from `scraping/data/index.json` at build time
- [x] Populate departments page with list of departments
