### ISSUE TITLE
Department page

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#20]
## Description

- **As a** student,
- **I want** to see a list of courses in a department,
- **So that** I can navigate the site in a familiar way (similar to the actual catalog).

## Tasks

- [x] #18
- [x] Create empty department page with dynamic route
- [x] Write JSON Lines parsing utility
- [x] Use `getStaticPaths` to fetch department index from `scraping/data/index.json` and determine what paths are required at build time
- [x] Use `getStaticProps` to fetch department info from `scraping/data/[DEPT].jsonl` at build time
- [x] Populate department page with list of courses
