### ISSUE TITLE
Course descriptions

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#21]
## Description

- **As a** student,
- **I want** to see the original course descriptions,
- **So that** I can verify the information from the tool without needing to open the catalog.

## Tasks

- [x] Include course descriptions in scraping output
- [x] Include number of courses in each department in department index
- [x] Display descriptions on frontend
