### ISSUE TITLE
Course page

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#29]
## Description

- **As a** student,
- **I want** to view a course's prerequisites in a graphical format,
- **So that** I can analyze and understand them in a potentially more helpful visual way.

## References

- https://datalanguage.com/blog/graphical-uis-with-svg-and-react-part-1-declarative-graphics

## Tasks

- [x] Copy scraped data into `public` folder for local development
- [x] Fetch course index and department file
- [x] Display course info and description
- [x] #33
- [x] Store department data during builds with an in-memory cache
- [x] Store course data at runtime with an in-memory cache
- [x] #32
- [x] Add panning capability to graph viewer
- [x] Create 404 page
- [x] Set color scheme
- [x] Test on different browsers
- [x] #35
