### ISSUE TITLE
Successor courses

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#30]
## Description

- **As a** student,
- **I want** to know, for a given course _C_, which other courses have _C_ as an immediate prerequisite,
- **So that** I can prioritize highly connected courses when planning my schedule.

## Tasks

- [x] Compute successor relationships during postprocessing step (ignore cycles for now)
- [x] Store lists of successors in output
- [x] Display sorted successor list in course page
- [x] Display number of successors in course listings
