### ISSUE TITLE
Draw prerequisite graph as SVG

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#32]
## Tasks

- [x] Add type definitions to represent graph nodes
- [x] Create graph SVG components to draw a hardcoded prerequisite graph
- [x] Write a function to recursively calculate positions of graph nodes
- [x] Add a reducer to `GraphViewer` which handles showing and hiding the tree rooted at a particular graph node
