### ISSUE TITLE
Update scraping output structure

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#33]
## Description

Due to some restrictions with the Next.js static build process and in anticipation of certain future features, we will revise the structure and format of our scraping output to be as follows:

Directory structure:
```
scraping/
 |- intermediate/    (ignore or delete during cleanup)
 |   |- departments.jsonl
 |   |- CSE.jsonl
 |   `- other JSON Lines files...
 |- data/
 |   |- departments.json
 |   |- CSE_100.json
 |   `- other course data files...
 `- Python scripts...
```
- This structure simplifies the build process compared to the current implementation
- The `data` folder will be copied into the `public` folder when building, to provide random access from the frontend; this should be added to the `.gitignore`

`departments.json` format:
```json
{
  "CSE": {
    "code": "CSE",
    "name": "Computer Science and Engineering",
    "link": "https://...",
    "courses": [
      "CSE 4",
      "CSE 100",
      "..."
    ]
  },
  // ...
}
```
- Similar to current `index.json`, without course to department mappings

Course JSON file format:
```json
{
  "code": "CSE 100",
  "title": "Advanced Data Structures",
  "units": "4",
  "dept": "CSE",
  "anchor": "cse100",
  "description": "...",
  "prereqs": { ... },
}
```
- Plus optional `coreqs` field
- Add `leadsto` field in the future

## Tasks

- [x] Update Scrapy pipeline to keep `dept` field
- [x] Update postprocessor to output final data as described above and remove intermediate files
- [x] Update build script to copy data into `public` directory
- [x] Add `public/data` to `.gitignore`
- [x] Update `getStaticPaths` and `getStaticProps` in the departments page
