### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#38]
## Description

- **As a** student,
- **I want** to search for a course by course code,
- **So that** I can find the information I need as quickly as possible.

This version will just have basic prefix search on course codes. Future versions may implement some kind of fuzzy searching and searching on course titles/descriptions.

## Tasks

- [x] Create `/search` page that accepts search text query parameter
- [x] Read in all course codes in `getStaticProps`
- [x] Search for the query in the list of course codes (prefix search)
- [x] Get matched courses from frontend cache and display in a list below the search bar (no pagination for now)
