### ISSUE TITLE
Custom domain name

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#39]
## Description

- Host this project at its own domain, e.g. `coursegrapher.net`

## Tasks

- [x] Finalize name of project (GrAPE)
- [x] Register new domain name
- [x] Configure repository to use the domain (see https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages)
- [x] Remove `/course-grapher` base path
- [x] Add site favicon
