### ISSUE TITLE
Scraping statistics file

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#46]
## Description

- Output an additional JSON file from the scraper containing statistics
  - Date and time of scraping
  - Total number of departments
  - Total number of courses
  - Number of courses with prerequisites
  - Number of courses with corequisites
  - Number of courses with successors
- Consider displaying these statistics on the frontend somewhere

## Tasks

- [x] Add any missing metrics
- [x] Output statistics to JSON
- [x] Add statistics to About page
