### ISSUE TITLE
Corequisites

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#47]
## Description

- **As a** student,
- **I want** a course's corequisites to be shown in its graph,
- **So that** I can better understand the requirements I need to meet in order to take that course.

## Tasks

- [x] Update type definitions to store bounds of both node types
- [x] Rewrite `setPositions` to lay out nodes more optimally
- [x] Update type definitions to include corequisites
- [x] Account for corequisites in `setPositions`
- [x] Render corequisites in `CourseNode`
