### ISSUE TITLE
Course catalog spider

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#5]
## Description

- Write a web crawler/spider using [Scrapy](https://docs.scrapy.org/en/latest/index.html) that scrapes course information from the [UCSD course catalog](https://catalog.ucsd.edu/front/courses.html)
  - Access each department's course list linked from that page
  - Extract the following basic information about each course:
    - Course number
    - Title
    - Number of units
  - Save the information to a JSON file (one file per department)
- The next step will be to write a CLI for running the spider

## Tasks

- [x] Create spider class
- [x] Crawl the catalog front page for links to course list pages only (ignore programs, faculty, etc.)
- [x] Crawl each course list and extract info
- [x] Save info as JSON
- [x] Add log messages
- [x] Handle as much malformed/nonstandard data as possible
- [x] Count metrics and print them when finished
