### ISSUE TITLE
Search bar accessibility

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#51]
## Description

Updating the search bar feature:
- Change to `<input type="search">`
- Add an explicit label (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#labels)
- Remove or change placeholder value
- ~~Consider adding an explicit submit button~~ Probably unnecessary

## Tasks

- [x] Change input type
- [x] Add and style label
- [x] Change placeholder to example value
- [x] Show loading message while search is executing
- [x] Add link to search page in navigation bar
