### ISSUE TITLE
Miscellaneous parser improvements

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#56]
## Description

- Handle this case: "Prerequisites: One of XYZ 10A-B or ..." should yield `{ one of: "XYZ 10A", "XYZ 10B", ... }`, not `{ one of: { all of: "XYZ 10A", "XYZ 10B" }, ... }`
- Handle this case: "Prerequisites: concurrent enrollment in ABC 123" should yield ABC 123 as a corequisite, not a prerequisite
- Move counting of course statistics to postprocessing
- Replace en dashes with hyphens in file names

## Tasks

- [x] Handle one-of case
- [x] Handle concurrent enrollment case
- [x] Move statistics counting
- [x] Replace en dashes
