### ISSUE TITLE
Catalog spider CLI

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#6]
## Description

- **As a** maintainer,
- **I want** to run the catalog spider via the command line,
- **So that** I can set options and get results with minimal hassle.

More info:

- Write a CLI using the [argparse](https://docs.python.org/3/library/argparse.html) module for interacting with the catalog spider
- Support the following options:
  - Log level
  - Log file
  - Log disable
  - _Consider_: Data output path

## Tasks

- [x] Create CLI script with basic functionality (runs spider with default options)
- [x] Allow setting log level
- [x] Allow setting log file
- [x] Allow disabling logs
