### ISSUE TITLE
Parse prerequisites

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#7]
## Description

- Extend spider functionality to parse course prerequisites

## Tasks

- [x] Get course descriptions and match to titles
- [x] Extract prerequisite lists from descriptions
- [x] Normalize prerequisites and remove false positives
- [x] Design data structure for prerequisite sets
- [x] Generate prerequisite set structure from normalized string
- [x] Write info to output
