### ISSUE TITLE
Automated parser unit tests

### ISSUE THREAD

**Issue by wllmwu** [wllmwu/course-grapher#9]
## Description

- Add a Python script that runs unit tests on the course info parser
- This will serve as regression testing and also document variations in syntax/structure that have been observed in the real catalog

## Tasks

- [ ] Add tests script
- [ ] Write title line parser tests
- [ ] Write prerequisite parser tests
